FROM nginx:alpine

# Remove default files
RUN rm -rf /usr/share/nginx/html/*

# Copy our custom config
COPY ./nginx/default.prod.conf /etc/nginx/conf.d/default.conf

# Copy built frontend files
COPY --from=notebookllm-prod-frontend:latest /usr/share/nginx/html/ /usr/share/nginx/html/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]